### ISSUE TITLE
Error get-lexer: 'before-lang-line

### ISSUE THREAD

**Issue by JJPro** [jeapostrophe/racket-langserver#12]
#### Error:
```sh 
Caught exn in request "textDocument/documentSymbol"
get-lexer: 'before-lang-line
  context...:
   .../racket-langserver/text-document.rkt:233:0: document-symbol
```

The above error will throw when `#lang ..` is absent or when there are comments ahead of `#lang ..`

**Comment by engmrgh** [comment]
I'm facing almost the same issue:
`
Caught exn in request "textDocument/documentSymbol"
get-lexer: 'before-lang-line

[Error - 11:58:25 PM] Request textDocument/documentSymbol failed.
  Message: internal error in method "textDocument/documentSymbol"
  Code: -32603 
`

**Comment by Eugleo** [comment]
This issue got reported multiple times on the Magic Racket repo as well; I’ll link the respective issues and their authors below:

- https://github.com/Eugleo/magic-racket/issues/23 by @togna

**Comment by engmrgh** [comment]
Thank you @Eugleo for the response, seem the solution is to add `#lang racket` in the second line based on links provided.

**Comment by Eugleo** [comment]
Yeah, but still the langserver probably should report that in some sensoble way, not just throw a random exception. That's the reason I'm reporting this, anyway.

**Comment by silesky** [comment]
I'm getting this error when doing the first exercise in `beautiful racket`.

I'm getting this when placing #lang  racket on the second line

![image](https://user-images.githubusercontent.com/5115498/98739676-65ba9200-236f-11eb-96b3-b1c3d9ff9ab5.png)

**Comment by aymanosman** [comment]
The [`read-accept-reader`](https://docs.racket-lang.org/reference/Reading.html?q=read-accept-reader#%28def._%28%28quote._~23~25kernel%29._read-accept-reader%29%29) parameter controls this.

**Comment by silesky** [comment]
@aymanosman I am not sure this is the right issue for this — but I’m actually following up on this bug: https://github.com/Eugleo/magic-racket/issues/24

**Comment by aymanosman** [comment]
I think you problem is different.

Forget what I said above.

What you have is an actual syntax error. You must be following the tutorial wrong.

![Screen Shot 2020-11-13 at 14 05 39](https://user-images.githubusercontent.com/3605049/99080515-53339900-25b9-11eb-9007-d53530bd55de.png)

**Comment by jeapostrophe** [comment]
Hi everyone,

I think that the `before-lang-line` is best fixed by adding a case to `text-document.rkt`'s function `get-lexer` that tests if the `lexer` is `'before-lang-line` and just returns the `racket-lexer` again, or potentially just always gives back the `racket-lexer` if the return result is not a `procedure?`.

For @aymanosman 's error, this message is not coming from the language server, it is coming from `br/quicklang`, which is reading the syntax of its body without `read-accept-reader` turned on. This behavior is good and expected for `br/quicklang`, because it doesn't make sense for a file to have multiple `#lang` lines.
