### ISSUE TITLE
Semantic coloring

### ISSUE THREAD

**Issue by dvc94ch** [jeapostrophe/racket-langserver#3]
A proposal for LSP is in the works. theia-ide/theia#1845 https://github.com/Microsoft/language-server-protocol/pull/124
Here someone implemented the hack I initially proposed https://github.com/rust-lang-nursery/rls/issues/85

**Comment by Eugleo** [comment]
@jeapostrophe I think the LSP has already included semantic coloring, see [link to VSCode docs](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-provider). It would be cool to have something like this, regexes aren't very good for things like quasiquotes or macros.

**Comment by MLavrentyev** [comment]
Once that's added (if it is), here's some resources on how to get the colorer from the #lang. You probably want to get the language info using:

```racket
(define lang-info (read-language (open-input-string (send doc-text get-text))))
(lang-info 'color-lexer #f)
```

The relevant docs can be found [here](https://docs.racket-lang.org/tools/lang-languages-customization.html#%28elem._color-lexer%29).

Based on [this comment](https://github.com/microsoft/language-server-protocol/issues/18#issuecomment-721372490) it seems the current 3.16 version of the LSP [supports semantic coloring](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_semanticTokens). I'm going to take a look into doing this and see if we can add this, since I think it's necessary to do coloring on the server side to support custom #langs.

**Comment by 6cdh** [comment]
I'm interested in implement semantic tokens recently.

For convenience, all tokens in [specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens).

These are my rough idea:

## Design

### Supported Tokens

The following tokens will be supported

| token/language |     information source      |
| :------------: | :-------------------------: |
|    variable    |       lexer (symbol)        |
|    comment     |       lexer (comment)       |
|     string     |       lexer (string)        |
|     number     |       lexer (number)        |
|     regexp     |  lexer (regexp or pregexp)  |
|   parameter    | manually walk syntax object |
|    function    | manually walk syntax object |

modifiers:

| modifiers  |           information source            |
| :--------: | :-------------------------------------: |
| definition | drracket syncheck:add-definition-target |

### Requests

|   method   | support |
| :--------: | :-----: |
|    full    |   Yes   |
| full/delta |   Yes   |
|   range    |   Yes   |
|  refresh   |   No    |

## Prototype

I wrote a simple prototype: [snippet](https://gist.github.com/6cdh/c648f70ee53358893dbf127b62e0733a)

Note in this prototype, I used `read/syntax` not lexer, it don't recognize comments.

usage:

```shell
racket pt.rkt filename
```

Then it will print the tokens and their information in the order that they appear in the file.

**Comment by dannypsnl** [comment]
link PR: #133

**Comment by dannypsnl** [comment]
This can be closed as complete now.

**Comment by jeapostrophe** [comment]
Thanks!
